/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import DatabaseConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author soery
 */
public class formRegister extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogSuccesRegister = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        words = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        titleUser = new javax.swing.JLabel();
        TitleNama = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldUser = new javax.swing.JTextField();
        titlePass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        titleConfirmPass = new javax.swing.JLabel();
        fieldConfirmPass = new javax.swing.JPasswordField();
        BGRegister = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        words1 = new javax.swing.JLabel();
        registButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(230, 194, 65));

        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Registration Successful!");

        loginButton.setBackground(new java.awt.Color(230, 194, 65));
        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Log in to continue.");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        words.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        words.setForeground(new java.awt.Color(255, 255, 255));
        words.setText("Welcome to the system.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(title)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(words)
                    .addComponent(loginButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogSuccesRegisterLayout = new javax.swing.GroupLayout(jDialogSuccesRegister.getContentPane());
        jDialogSuccesRegister.getContentPane().setLayout(jDialogSuccesRegisterLayout);
        jDialogSuccesRegisterLayout.setHorizontalGroup(
            jDialogSuccesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogSuccesRegisterLayout.setVerticalGroup(
            jDialogSuccesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Register Your Future!");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 240, 50));

        titleUser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        titleUser.setText("Username: ");
        jPanel1.add(titleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, -1));

        TitleNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TitleNama.setText("Full Name: ");
        jPanel1.add(TitleNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, -1));

        fieldName.setBackground(new java.awt.Color(246, 246, 246));
        fieldName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fieldName.setName(""); // NOI18N
        jPanel1.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 220, -1));

        fieldUser.setBackground(new java.awt.Color(246, 246, 246));
        fieldUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fieldUser.setName(""); // NOI18N
        jPanel1.add(fieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 220, -1));

        titlePass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        titlePass.setText("Password: ");
        jPanel1.add(titlePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 60, -1));

        fieldPass.setBackground(new java.awt.Color(246, 246, 246));
        fieldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fieldPass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 220, 20));

        titleConfirmPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        titleConfirmPass.setText("Confirm Password: ");
        jPanel1.add(titleConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 100, 20));

        fieldConfirmPass.setBackground(new java.awt.Color(246, 246, 246));
        fieldConfirmPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fieldConfirmPass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 20));

        BGRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jPanel1.add(BGRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 290, 370));

        registerButton.setBackground(new java.awt.Color(255, 234, 133));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 30));

        words1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        words1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        words1.setText("Already have Account?");
        jPanel1.add(words1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, 20));

        registButton.setBackground(new java.awt.Color(230, 194, 65));
        registButton.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        registButton.setForeground(new java.awt.Color(93, 173, 226));
        registButton.setText("Login");
        registButton.setBorder(null);
        registButton.setContentAreaFilled(false);
        registButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registButtonMouseClicked(evt);
            }
        });
        registButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
          String namaUser = fieldName.getText();
        String idUser = fieldUser.getText();
        String password = new String(fieldPass.getPassword());
        String confirmPassword = new String(fieldConfirmPass.getPassword());
        
        if(!confirmPassword.equals(password)) {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password tidak Sesuai", "Pesan Salah", JOptionPane.ERROR_MESSAGE);
            fieldConfirmPass.setText("");
            fieldConfirmPass.requestFocus();
        } else {
            try (Connection conn = DBConnection.konek()) {
                String query = "INSERT INTO pengguna (namaPengguna, username, password)" +
                        "VALUES (?, ?, ?)";
                
                PreparedStatement pstmt = conn.prepareStatement(query);

                // Set nilai parameter query
                pstmt.setString(1, namaUser);
                pstmt.setString(2, idUser);
                pstmt.setString(3, password);

                int resultSet = pstmt.executeUpdate();

                if (resultSet > 0) { // Jika ada hasil, registrasi berhasil
                    JOptionPane.showMessageDialog(null, "Registrasi Akun berhasil, kembali ke page login");
                    new formLogin().setVisible(true);
                    dispose();
                } else { // Jika tidak ada hasil, login gagal
                    JOptionPane.showMessageDialog(null, "ID atau Password salah!", "Pesan Salah", JOptionPane.ERROR_MESSAGE);
                    fieldName.setText("");
                    fieldUser.setText("");
                    fieldPass.setText("");
                    fieldConfirmPass.setText("");
                    fieldName.requestFocus();
                }
                
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registButtonActionPerformed
        new formLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_registButtonActionPerformed

    private void registButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registButtonMouseClicked
         new formLogin().setVisible(true);
       dispose();
    }//GEN-LAST:event_registButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGRegister;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleNama;
    private javax.swing.JPasswordField fieldConfirmPass;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JDialog jDialogSuccesRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleConfirmPass;
    private javax.swing.JLabel titlePass;
    private javax.swing.JLabel titleUser;
    private javax.swing.JLabel words;
    private javax.swing.JLabel words1;
    // End of variables declaration//GEN-END:variables
}
